In [1]:
import numpy as np
import scipy.linalg as la
import pandas as pd
np.set_printoptions(suppress=True)

In [2]:
def load_object_vertices(filename):
    df = pd.read_csv(filename, header=None, delimiter=' ')
    vertices = df.loc[df[0] == 'v', 1:].values.astype(np.float64)
    # append 1 to each vertex
    return np.hstack((vertices, np.ones((vertices.shape[0], 1))))

In [3]:
a, b = load_object_vertices('resources/bunny2.obj'), load_object_vertices('resources/bunny2_trans.obj')

In [4]:
a.shape, b.shape

((14290, 4), (14290, 4))

In [5]:
a.T @ a

array([[ 4118.01034397, -1015.80105369,  -118.4702156 , -1793.03703061],
       [-1015.80105369,  4939.86827488,  -984.15225541, -3149.72391525],
       [ -118.4702156 ,  -984.15225541,  2030.41484368,  1842.91859957],
       [-1793.03703061, -3149.72391525,  1842.91859957, 14290.        ]])

In [6]:
a.T @ b

array([[   60.87463481,  -507.9005364 ,  2058.95737488, -1793.03703061],
       [  491.6715955 ,  2469.93411963,  -508.29219602, -3149.72391525],
       [-1015.25430629,  -492.07612277,   -58.42671704,  1842.91859957],
       [ -922.17292097, -1574.86195052,  -895.78452862, 14290.        ]])

In [7]:
lu, piv = la.lu_factor(a.T @ a)

In [8]:
piv, lu

(array([0, 1, 2, 3], dtype=int32),
 array([[ 4118.01034397, -1015.80105369,  -118.4702156 , -1793.03703061],
        [   -0.24667278,  4689.2978065 , -1013.37563267, -3592.01734166],
        [   -0.0287688 ,    -0.21610392,  1808.01215226,  1015.08605187],
        [   -0.43541344,    -0.76600325,     0.56143763, 10187.8831392 ]]))

In [9]:
x = la.lu_solve((lu, piv), a.T @ b)

In [10]:
x

array([[ 0.00039814, -0.        ,  0.49999985,  0.        ],
       [ 0.00000001,  0.49999999, -0.        ,  0.        ],
       [-0.49999986,  0.        ,  0.00039813,  0.        ],
       [ 0.        , -0.        , -0.        ,  1.        ]])

In [11]:
(x.T @ a.T).T - b

array([[-0.00000023,  0.        , -0.00000036, -0.        ],
       [ 0.00000004, -0.0000005 , -0.00000028,  0.        ],
       [ 0.00000037, -0.0000005 , -0.00000044, -0.        ],
       ...,
       [ 0.00000001, -0.        ,  0.00000004,  0.        ],
       [ 0.00000038,  0.0000005 , -0.00000043,  0.        ],
       [-0.00000016, -0.        ,  0.00000035,  0.        ]])

In [12]:
a @ x - b

array([[-0.00000023,  0.        , -0.00000036, -0.        ],
       [ 0.00000004, -0.0000005 , -0.00000028,  0.        ],
       [ 0.00000037, -0.0000005 , -0.00000044, -0.        ],
       ...,
       [ 0.00000001, -0.        ,  0.00000004,  0.        ],
       [ 0.00000038,  0.0000005 , -0.00000043,  0.        ],
       [-0.00000016, -0.        ,  0.00000035,  0.        ]])